### ISSUE TITLE
yml file not exist

### ISSUE THREAD

**Issue by Miracutor** [cardinalby/schedule-job-action#6]
I followed your instructions on Readme and created `.github-scheduled-workflows/example.yml` on the root of my repo.
When I tried to refer to the file later for `templateYmlFile` input, it failed.
```yml
- uses: cardinalby/schedule-job-action@v1
  with:
      ghToken: ${{ github.token }}
      templateYmlFile: '.github-scheduled-workflows/example.yml'
```
The error that show up:
```
Error: /home/runner/work/repo-name/repo-name/.github-scheduled-workflows/example.yml file doesn't exist
```
Is repo-name is supposed to repeat twice in path or maybe I misunderstanding something?
